name: GitHub Actions Demo
on: [push]
jobs:
  run-make-file:
    runs-on: ubuntu-latest
    
    steps:
     - name: clone repo    
       uses: actions/checkout@v1
              
     - name: run make file
       run: make say-hello
